Prototype
vancho-go/gophermart pull request #1
Opened 2023-12-04 10:42 UTC by vancho-go

2023-12-30 01:41 UTC, s-shpak requested changes

2023-12-30 01:41 UTC, s-shpak commented on cmd/gophermart/main.go
> +		log.Fatalf("error building server configuration: %s", err.Error())
```suggestion
		log.Fatalf("error building server configuration: %v", err)
```

2023-12-30 01:41 UTC, s-shpak commented on cmd/gophermart/main.go
> +	go periodicUpdateExecutor(ctx, time.Millisecond*500, configuration.AccrualSystemAddress, dbInstance.HandleOrderNumbers, logger)
Лучше вынести `time.Millisecond * 500` в костанту, чтобы было понятно, что можно параметризовать в программе

2023-12-30 01:41 UTC, s-shpak commented on cmd/gophermart/main.go
> +			// не обработана 400 ошибка
Нормально ли, что она не обработана?

2023-12-30 01:41 UTC, s-shpak commented on internal/app/auth/jwt.go
> +	secretKey = "temp_secret_key"
Получается, что возможно использовать только этот ключ ?

2023-12-30 01:41 UTC, s-shpak commented on internal/app/auth/jwt.go
> +func isTokenValid(tokenString string) bool {
Почему бы вместо `bool` не возвращать ошибку, чтобы возможно было залогировать ее и получить больше информации о причине возникновения ?

2023-12-30 01:41 UTC, s-shpak commented on internal/app/auth/middleware.go
> +type contextKey string
Лучше использовать `int` и `iota`, как здесь: https://stackoverflow.com/questions/40891345/fix-should-not-use-basic-type-string-as-key-in-context-withvalue-golint

2023-12-30 01:41 UTC, s-shpak commented on internal/app/config/config.go
> +	flag.StringVar(&databaseURI, "d", "host=localhost port=5432 user=vancho password=vancho_pswd dbname=vancho_db sslmode=disable", "connection string for driver to establish connection to he DB")
Не стоит хардкодить даже дефолтные пароли

2023-12-30 01:41 UTC, s-shpak commented on internal/app/config/config.go
> +	if envServerRunAddress := os.Getenv("RUN_ADDRESS"); envServerRunAddress != "" {
Здесь стоит использовать `LookupEnv`, т.к. пустое значение может иметь какую-то семантику с т.з. бизнес-логики

2023-12-30 01:41 UTC, s-shpak commented on internal/app/handlers/handlers.go
> +			logger.Info("registerUser:", zap.Error(err))
Логировать стоит только ошибки с кодом 5**, все остальные - штатные ошибки сервера, которые можно отдавать клиенту без логирования

2023-12-30 01:41 UTC, s-shpak commented on internal/app/handlers/ordernumberverifier.go
> +func isOrderNumberValid(orderNumber string) (bool, error) {
Судя по тому, как ты используешь эту функцию, она может возвращать только ошибку

2023-12-30 01:41 UTC, s-shpak commented on internal/app/handlers/ordernumberverifier.go
> +	reversedOrderNumber := reverseString(cleanOrderNumber)
Зачем разворачивать строку, нельзя ли ее просто прочитать с конца ?

2023-12-30 01:41 UTC, s-shpak commented on internal/app/logger/logger.go
> +func NewLogger(logLevel string) (Logger, error) {
Почему бы не использовать `zap`-логгер напрямую ? Зачем тебе дополнительный интерфейс ?

2024-01-07 11:05 UTC, vancho-go commented on cmd/gophermart/main.go
> +			// не обработана 400 ошибка
Забыл убрать комментарий

2024-01-07 12:02 UTC, vancho-go commented on internal/app/logger/logger.go
> +func NewLogger(logLevel string) (Logger, error) {
видел в пачке вариант такого использования логгера

2024-01-07 12:09 UTC, merged